name: travel
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.3
  get: ^4.5.1
  google_fonts: ^2.1.0
  # embedded maps
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.3.0
  location: ^4.4.0
  flutter_svg: ^1.1.0
  geolocator: ^9.0.2
  #login with gg account
  google_sign_in: ^6.1.4
  # api
  http: ^0.13.5
  dio: ^5.1.2
  # save data on device
  shared_preferences: ^2.0.10
  # model
  tflite: ^1.1.2
  image_picker: ^0.8.4+11
  # permission_handler: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "assets/images/travel.png" 
  android: true
  ios: true

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/bbq/
    - assets/images/aveni/
    - assets/images/chay/
    - assets/images/DLG/
    - assets/images/fivitel/
    - assets/images/galaxy/
    - assets/images/hyatt/
    - assets/images/indian/
    - assets/images/quang/
    - assets/images/radisson/
    - assets/images/si/
    - assets/images/taco/
    - assets/images/tiki/
    - assets/images/bana/
    - assets/images/vincom/
    - assets/images/3d/
    - assets/images/asian/
    - assets/images/thantai/


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
